[package]
name = "hpke"
repository = "https://github.com/rozbb/rust-hpke"
documentation = "https://docs.rs/rust-hpke"
description = "An implementation of the HPKE hybrid encryption standard in pure Rust"
readme = "README.md"
version = "0.1.7"
authors = ["Michael Rosenberg <michael@mrosenberg.pub>"]
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["cryptography", "key-exchange", "encryption", "aead"]
categories = ["cryptography", "no-std"]

[features]
# "p256" enables the use of ECDH-NIST-P256 as a KEM
# "x25519" enables the use of the X25519 as a KEM
default = ["p256", "x25519"]
# The std feature has no function outside of doing KAT tests. There is no need to use this in
# production.
std = []

[dependencies]
aead = "0.3"
aes-gcm = "0.6"
byteorder = { version = "1.3", default-features = false }
chacha20poly1305 = "0.5"
digest = "0.9"
hkdf = "0.9"
rand = { version = "0.7", default-features = false }
p256 = { version = "0.3", default-features = false, features = ["arithmetic"], optional = true}
sha2 = { version = "0.9", default-features = false }
subtle = { version = "2.2", default-features = false }

[dependencies.x25519-dalek]
version = "0.6"
default-features = false
features = ["u64_backend"]
optional = true

[dev-dependencies]
hex = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = { version = "0.7", default-features = false, features = ["getrandom"] }

[[example]]
name = "client_server"
required-features = ["x25519"]

[[example]]
name = "agility"
required-features = ["p256", "x25519"]
