[package]
name = "hpke"
repository = "https://github.com/rozbb/rust-hpke"
documentation = "https://docs.rs/rust-hpke"
description = "An implementation of the HPKE hybrid encryption standard in pure Rust"
readme = "README.md"
version = "0.8.0"
authors = ["Michael Rosenberg <michael@mrosenberg.pub>"]
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["cryptography", "crypto", "key-exchange", "encryption", "aead"]
categories = ["cryptography", "no-std"]

[features]
# "p256" enables the use of ECDH-NIST-P256 as a KEM
# "x25519" enables the use of the X25519 as a KEM
default = ["p256", "x25519"]
x25519 = ["x25519-dalek"]
# Include serde Serialize/Deserialize impls for all relevant types
serde_impls = ["serde", "generic-array/serde"]
# The std feature has no function outside of doing KAT tests. There is no need to use this in
# production.
std = []

[dependencies]
aead = "0.4"
aes-gcm = "0.9"
byteorder = { version = "1.4", default-features = false }
chacha20poly1305 = "0.9"
generic-array = { version = "0.14", default-features = false }
digest = "0.9"
hkdf = "0.11"
rand_core = { version = "0.6", default-features = false }
p256 = { version = "0.9", default-features = false, features = ["arithmetic", "ecdh", "zeroize"], optional = true}
sha2 = { version = "0.9", default-features = false }
serde = { version = "1.0", default-features = false, optional = true }
subtle = { version = "2.4", default-features = false }
zeroize = { version = "1.3", default-features = false, features = ["zeroize_derive"] }

[dependencies.x25519-dalek]
version = "1.2"
default-features = false
features = ["u64_backend"]
optional = true

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
hex = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = { version = "0.8", default-features = false, features = ["getrandom", "std_rng"] }

[[example]]
name = "client_server"
required-features = ["x25519"]

[[example]]
name = "agility"
required-features = ["p256", "x25519"]

# Tell docs.rs to build docs with `--all-features`
[package.metadata.docs.rs]
all-features = true

# Criteron benches
[[bench]]
name = "benches"
harness = false

[lib]
bench = false

