name: CI

on:
  push:
    branches: [ '**' ]
    paths-ignore: ["README.md"]
  pull_request:
    branches: [ '**' ]
    paths-ignore: ["README.md"]

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install Cargo Hack
        run: cargo install cargo-hack --debug --locked

      - name: Run cargo hack test
        env:
          RUSTFLAGS: -D warnings -A dead_code -A unused
        run: cargo hack test --feature-powerset --features std,alloc # always enable std and alloc to reduce features explosion

      - name: Run cargo build with all features
        env:
          RUSTFLAGS: -D warnings
        run: cargo build --all-features

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  # Enable this once x25519-dalek has another 2.0-pre.X release
  #msrv:
  #  name: Current MSRV is 1.65.0
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v3
  #  # First run `cargo +nightly -Z minimal-verisons check` in order to get a
  #  # Cargo.lock with the oldest possible deps
  #  - uses: dtolnay/rust-toolchain@nightly
  #  - run: cargo -Z minimal-versions check --all-features
  #  # Now check that `cargo build` works with respect to the oldest possible
  #  # deps and the stated MSRV
  #  - uses: dtolnay/rust-toolchain@1.65.0
  #  - run: cargo build --all-features

  check:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: Install Cargo Hack
        run: cargo install cargo-hack --debug --locked

      - name: Run cargo hack clippy
        if: ${{ matrix.toolchain == 'stable' }}
        run: cargo hack clippy --feature-powerset -- -D warnings -A dead_code -A unused

      - name: Run cargo hack check
        if: ${{ matrix.toolchain != 'stable' }}
        env:
          RUSTFLAGS: -D warnings -A dead_code -A unused
        run: cargo hack check --feature-powerset

      - name: Run cargo clippy with all features and warnings
        if: ${{ matrix.toolchain == 'stable' }}
        run: cargo clippy --all-features -- -D warnings
